// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/apple-touch-icon.png"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/favicon.svg"
    | "/hero/cassette-route.webp"
    | "/icon/128.png"
    | "/icon/16.png"
    | "/icon/48.png"
    | "/popup.html"
    | "/robots.txt"
    | "/sitemap.xml"
    | "/staticwebapp.config.json"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
